---
title: "Journal 1"
#bibliography: references.bib
author: "Dávid Sümeghy"
output: 
  html_document:
    css: tweaks.css
    toc:  true
    toc_float: true
    number_sections: false
    
---

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

----
```{r}
rm(list = ls())
```

```{r}
fsave <- function(x, file, location = "./data/processed/", ...) {
    if (!dir.exists(location))
        dir.create(location)
    datename <- substr(gsub("[:-]", "", Sys.time()), 1, 8)
    totalname <- paste(location, datename, file, sep = "")
    print(paste("SAVED: ", totalname, sep = ""))
    save(x, file = totalname)
}

fpackage.check <- function(packages) {
    lapply(packages, FUN = function(x) {
        if (!require(x, character.only = TRUE)) {
            install.packages(x, dependencies = TRUE)
            library(x, character.only = TRUE)
        }
    })
}

colorize <- function(x, color) {
    sprintf("<span style='color: %s;'>%s</span>", color, x)
}
```

```{r}
packages = c("rjson", "tidyverse", "ggplot2", "leaflet", "sf","osmdata","tidyverse")

fpackage.check(packages)
```

```{r}
elections <- rjson::fromJSON(file = "./data/tk2021.geo.json")
```

```{r}
# this is a bit messy. tidyverse  would be welcome

# retrieve the data
test <- lapply(elections[["features"]], `[[`, 2)
js_df <- sapply(test, function(x) as.data.frame(x))
library(plyr)
js_df <- ldply(js_df, data.frame)
detach("package:plyr", unload = TRUE)
```

```{r}
test <- lapply(elections[["features"]], `[[`, 3)
test <- lapply(test, "[[", 2)
js_df$long <- sapply(test, function(x) x[1])
js_df$lat <- sapply(test, function(x) x[2])
```

```{r}
names(js_df) <- c("Stembureau", "Adres", "Locatie", "description", "Geldige.stemmen", "Opgeroepen", "Ongeldig",
    "Blanco", "Geldige.stempassen", "Geldige.volmachtbewijzen", "Geldige.kiezerspassen", "Toegelaten.kiezers",
    "Meer.getelde.stembiljetten", "Minder.getelde.stembiljetten", "Meegenomen.stembiljetten", "Te.weinig.uitgereikte.stembiljetten",
    "Te.veel.uitgereikte.stembiljetten", "Geen.verklaring", "Andere.verklaring", "Te.veel.briefstembiljetten",
    "Geen.briefstembiljetten", "VVD", "PVV", "CDA", "D66", "GL", "SP", "PvdA", "CU", "PvdD", "PLUS50",
    "SGP", "DENK", "FvD", "BIJ1", "JA21", "CODE.ORANJE", "Volt", "NIDA", "Piratenpartij", "LP..Libertaire.Partij.",
    "JONG", "Splinter", "BBB", "NLBeter", "Lijst.Henk.Krol", "OPRECHT", "JEZUS.LEEFT", "Trots.op.Nederland..TROTS.",
    "U.Buntu.Connected.Front", "Blanco..Zeven..A.J.L.B..", "Partij.van.de.Eenheid", "Wij.zijn.Nederland",
    "gmcode", "election", "electionName", "DE.FEESTPARTIJ..DFP.", "Modern.Nederland", "Vrij.en.Sociaal.Nederland",
    "De.Groenen", "Partij.voor.de.Republiek", "long", "lat")
```

```{r}
# remove polling stations without coordinates (briefstembureaus mostly)
js_df %>%
    filter(!lat == 0) -> js_df2

# aggregate polling stations with same location
js_df2 %>%
    group_by(long, lat) %>%
    dplyr::summarise(Adres = first(Adres), Stembureau = first(Stembureau), description = first(description),
        gmcode = first(gmcode), across(Geldige.stemmen:Wij.zijn.Nederland, ~sum(.x, na.rm = TRUE))) ->
    js_df2

# remove polling station for which no voters were invited
print("polling stations without invited voters")
table(js_df2$Opgeroepen == 0, useNA = "always")
# lets throw these away
js_df2 %>%
    filter(!Opgeroepen == 0) -> js_df2

# filter polling stations where a lot more voters voted than were invited
suspicious<-js_df2 %>% 
  filter((Geldige.stemmen/Opgeroepen) > 1.1)

# remove polling stations without valid votes
suspicious %>%
    filter(!(Geldige.stemmen == 0)) -> suspicious
```

```{r}
amsterdam_uni <- opq ("Amsterdam, The Netherlands") %>% #geolocating supermarkets in Amsterdam
    add_osm_feature (key = "building", value = "university") %>%
    osmdata_sf ()

amsterdam_uni_polygons<-amsterdam_uni$osm_polygons 
```

```{r}
amsterdam_supermarket <- opq ("Amsterdam, The Netherlands") %>% #geolocating supermarkets in Amsterdam
    add_osm_feature (key = "building", value = "supermarket") %>%
    osmdata_sf ()

amsterdam_supermarket_points<-amsterdam_supermarket$osm_points 
```

```{r}
amsterdam_worship <- opq ("Amsterdam, The Netherlands") %>% #geolocating places of worship in Amsterdam
    add_osm_feature (key = "amenity", value = "place_of_worship") %>%
    osmdata_sf ()

amsterdam_worship_polygons<-amsterdam_worship$osm_polygons
```


```{r}
amsterdam_train <- opq ("Amsterdam, The Netherlands") %>% #geolocating train stations in Amsterdam
    add_osm_feature (key = "building", value = "train_station") %>%
    osmdata_sf ()

amsterdam_train_polygons<-amsterdam_train$osm_polygons 
```

```{r,eval=FALSE}
trainbuffer <-st_buffer(amsterdam_train_polygons,500) #creating buffers(500m)
unibuffer <-st_buffer(amsterdam_uni_polygons,500)
supermarketbuffer <-st_buffer(amsterdam_supermarket_points,500) 
worshipbuffer <-st_buffer(amsterdam_worship_polygons,500)

```

```{r,eval=FALSE}
suspicious_sf <- sf::st_as_sf(x = suspicious, coords = c("long", "lat"), crs =st_crs(amsterdam_train_polygons)) #matching projection
amsterdam_polling_stations<-suspicious_sf %>%  #filtering suspicious pollig stations Amsterdam
  filter(gmcode=="GM0363")
```

```{r,eval=FALSE}
leaflet(data = amsterdam_polling_stations) %>%
  leaflet::addTiles() %>% 
  leaflet::addProviderTiles(providers$Stamen.Toner) %>% 
  leaflet::addCircleMarkers(
  fillColor="red",
  color="black",
  fillOpacity = 0.8,
  radius = 5,
  label= ~description,
  group = "Show polling stations") %>% 
  leaflet::addPolygons(
    data=trainbuffer,
    fillColor="darkblue",
    color="black",
    group ="Show buffer area around train stations",
    label= ~name) %>% 
  leaflet::addPolygons(
    data=unibuffer,
    fillColor="green",
    color="black",
    group = "Show buffer area around university buildings") %>% 
    leaflet::addPolygons(
    data=supermarketbuffer,
    fillColor="yellow",
    color="black",
    group = "Show buffer area around supermarkets")%>% 
    leaflet::addPolygons(
    data=worshipbuffer,
    fillColor="pink",
    color="black",
    label=~name,
    group = "Show buffer area around places of worship") %>% 
    leaflet::addLayersControl(
    overlayGroups = c("Show polling stations","Show buffer area around train stations","Show buffer area around university buildings","Show buffer area around supermarkets","Show buffer area around places of worship"), 
    position = "topleft",
    options = leaflet::layersControlOptions(collapsed = FALSE))
```

```{r,eval=FALSE}
close_polling_stations <- st_intersection(trainbuffer,amsterdam_polling_stations) #finding polling stations inside the buffer areas around train stations
close_polling_stations_train<-close_polling_stations %>% 
distinct(Adres,.keep_all = TRUE)
```

```{r,eval=FALSE}
distances<-st_distance(amsterdam_polling_stations,amsterdam_train_polygons) #distance matrix
distances.df<-as.data.frame(distances)
colnames(distances.df) <- amsterdam_train_polygons$osm_id
rownames(distances.df) <- amsterdam_polling_stations$description
```


```


